import React from 'react';
import { Bell, AlertTriangle, Info, ShieldAlert, Clock } from 'lucide-react';
import { SystemAlert } from '../../types.js';

interface AlertsPanelProps {
  alerts: SystemAlert[];
}

export const AlertsPanel: React.FC<AlertsPanelProps> = ({ alerts }) => {
  return (
    <div className="p-4 lg:p-6 space-y-6 max-w-7xl mx-auto">
      <div className="bg-white border border-slate-200 p-4 rounded-xl flex items-center justify-between shadow-xs">
        <div>
          <h2 className="text-base font-extrabold text-slate-900 flex items-center gap-2">
            <Bell className="w-5 h-5 text-rose-600" />
            MUNICIPAL SYSTEM ALERTS & EVENT FEED
          </h2>
          <p className="text-xs text-slate-500">Real-time automated alerts generated by specialist agents and city sensors</p>
        </div>
      </div>

      <div className="space-y-3">
        {(alerts || []).map((alert) => {
          let badgeColor = 'bg-blue-50 text-blue-800 border-blue-200';
          let Icon = Info;

          if (alert.severity === 'CRITICAL') {
            badgeColor = 'bg-rose-50 text-rose-800 border-rose-200 animate-pulse';
            Icon = AlertTriangle;
          } else if (alert.severity === 'WARNING') {
            badgeColor = 'bg-amber-50 text-amber-800 border-amber-200';
            Icon = ShieldAlert;
          }

          return (
            <div
              key={alert.id}
              className="bg-white border border-slate-200 rounded-xl p-4 flex items-start justify-between gap-4 shadow-xs"
            >
              <div className="flex items-start space-x-3">
                <div className={`p-2 rounded-lg border ${badgeColor}`}>
                  <Icon className="w-5 h-5" />
                </div>

                <div>
                  <div className="flex items-center space-x-2">
                    <h4 className="font-extrabold text-sm text-slate-900">{alert.title}</h4>
                    <span className={`text-[10px] font-extrabold px-2 py-0.5 rounded border ${badgeColor}`}>
                      {alert.severity}
                    </span>
                  </div>
                  <p className="text-xs text-slate-700 font-medium mt-1">{alert.message}</p>
                </div>
              </div>

              <span className="text-[10px] text-slate-500 font-mono whitespace-nowrap flex items-center gap-1 font-semibold">
                <Clock className="w-3 h-3 text-slate-400" />
                {new Date(alert.timestamp).toLocaleTimeString()}
              </span>
            </div>
          );
        })}
      </div>
    </div>
  );
};
